package main;

import ventanas.VentanaPrincipal;

/*
 * PRACTICA APLICACION DE GESTION DE ESCRITORIO:
 * SIGUIENDO LOS CONCEPTOS Y EJEMPLOS MOSTRADOS CREAR UNA APLICACION DE GESTION
 * PARA UN NEGOCIO, EN LA CUAL SE GESTIONEN INFORMACIONES SOBRE CLIENTES Y
 * PRODUCTOS, EL PRODUCTO SERÁ EL DEL NEGOCIO A ELEGIR POR EL PROGRAMADOR,
 * DEBERA TENER AL MENOS 7 CAMPOS, Y DEBERA ESTAR ALMACENADO EN UNA TABLA DE
 * BASES DE DATOS.
 * 
 * LA GESTION DEBERA PERMITIR REGISTRAR, LISTAR, EDITAR Y BORRAR INFORMACIONES,
 * PERO EN ESTA TARDE SOLO SERA NECESARIO REGISTRAR.
 * 
 * OPCIONALES: 
 *  + USAR 3 CAMPOS DE ENTRADA NO ENSEÑADOS EN CLASE PARA EL PRODUCTO A ELEGIR
 *  	(POR EJEMPLO: CHECKBOX, LISTA DESPLEGABLE, RADIO BUTTONS)
 *  
 *  + INTENTAR REALIZAR UN LISTADO DE INFORMACIONES EN LOS PANELES DE LISTADO
 *  	(TABLAS, LISTS VIEW)
 */


public class Principal {
	//nuevo comentario
	public static void main(String[] args) {
		new VentanaPrincipal();
	}

}
